const message = {
  // title
  ANDROID: 'android',
  ADD_AUTHOR: 'ADD AUTHOR',
  LIVESTREAMS: 'LIVE STREAMS',
  LIVESTREAMS_DES: 'CONNECT & ENGAGE WITH US LIVE, FROM ANYWHERE IN THE WORLD',
  PARTNERS: 'PARTNERS',
  PARTNERS_DES:
    'Introducing our community partners who play an incredible role in our local and national tech scenes.',
  ANNOUNCEMENTS: 'Announcements',
  ANNOUNCEMENTS_DES: 'Read the latest news and announcements',
  ANNOUNNCEMENT_CATEGORY: 'Announcement categories',
  ANNOUNNCEMENT_CATEGORY_DES:
    'Read the latest news and announcement categories',
  EXHIBITORS: 'Exhibitors',
  EXHIBITORS_DES: 'Introducing our curated collection of exhibitors',
  EXHIBITORS_ADD: "Great to have you exhibit. Let's get your profile setup",
  SPONSORS: 'Sponsors',
  SPONSORS_BY: 'Sponsor By',
  SPONSORS_DES: 'Introducing our curated collection of sponsors',
  PRESENTATIOM_OVERVIEW: 'Presentation Overview',
  EPOSTER: 'ePoster',
  RELATEDTALKS: 'Related Talks',
  SIMILAR_SPEAKERS: 'Similar Speakers',
  SESSIONS: 'Sessions',
  SESSION_HEADER_DESCRIPTION: 'Our curated collection of sessions',
  TALK_ADD:
    "Thank you for wanting to present a Talk. Let's get your Talk submitted",
  SPONSOR_ADD: "Thank you for your support. Let's get your profile setup",
  OVERVIEW: 'Overview',

  // empty
  EMPTY: 'Empty',
  NO_SPEAKERS: 'There are no Speakers',
  NO_ANNOUNCEMENTS: 'There are no Announcements',
  NO_PARTNER: 'There are no Partners',
  NO_EXHIBITORS: 'There are no Exhibitors',
  NO_LIVESTREAM: 'There are no Livestream available today',
  NO_SPONSORS: 'There are no Sponsors',
  // validate
  TILE_REQUIRED: '* Tile is required',
  FILE_REQUIRED: '* File is required',
  EMAIL_REQUIRED: '* Email is required',
  NAME_REQUIRED: '* Name is required',
  DESCRIPTION_REQUIRED: '* Description is required',
  PASSWROD_REQUIRED: '* Password is required',
  INVALID_PARAMS: 'Invalid parameters',
  INCORRECT_EMAIL_PASSWORD: 'Incorrect email or password',
  INVALID_EMAIL: '* Invalid email address',
  THREAD_MIN_MEMBER: 'Please add at least a member',
  CANT_BE_BLANK: "Can't be blank",
  MIN_3_CHAR: 'Minimum is 3 characters',
  INVALID_URL: 'Invalid url',
  // common
  CANCEL_BUTTON: 'Cancel',
  OK_BUTTON: 'Ok',
  SIGN_OUT_BUTTON: 'Sign Out',
  WARNING: 'Warning',
  SIGN_OUT_DESCRIPTION: 'Do you want to sign out',
  SCHEDULE: 'Schedule',
  EVENT_MAP: 'Event Map',
  CHAT: 'Chat',
  PROFILE: 'Profile',
  VIEW_POSTER: 'View ePoster',
  SPEAKERS: 'Speakers',
  SPEAKER_HEADER_DESCRIPTION: 'Our curated collection of speakers',
  EDIT_QUESTION: 'Edit Question',
  ASK_A_QUESTION: 'ASK A QUESTION',
  INPUT_KNOW: 'What do you want to know?',
  DOCUMENTS: 'Documents',
  IMAGES: 'Images',
  NAME: 'Name',
  COMPANY: 'Company',
  DESCRIPTION: 'Description',
  FILE: 'File',
  SUPPORT_FILES:
    'File types supported: .jpg, .png, .gif, .pdf, mp3, .aac, .flac, .mp4, .avi, .mov, .qt, .wav, .doc,' +
    ' .docx, .xls, .xlsx, .ppt, .pptx, .ppts',
  MEDIA_UPLOAD: 'Upload Media',
  DOCUMENT_UPLOAD: 'Upload Document',
  FEATURED: 'Featured',
  FEATURED_ANNOTATION: 'Feature the Resource on the Resources index page',
  MEDIA_PICKER_TITLE: 'Select Media',
  ADD_QUESTION: 'Ask Question',
  ADD_RESOURCE: 'Add Resource',
  EDIT_RESOURCE: 'Update Resource',
  EDIT: 'Edit',
  DOWNLOAD: 'Download',
  FAVOURITE: 'Favourite',
  UNFAVOURITE: 'UnFavourite',
  CLOUDDOWNLOAD: 'cloud-download-1',
  DELETE: 'Delete',
  ADDITIONAL_INFORMATION: 'Additional Information',
  AUTHORS: 'AUTHORS',
  TALK_PLACEHOLDER: 'Select A Talk',
  QUESTION_PLACEHOLDER: 'Leave your question...',
  CHAT_PLACEHOLDER: 'Write a message',
  QUESTIONS: 'Questions',
  SUBMIT: 'Submit',
  LIVESTREAMS_AGENDA: 'Live Stream Agenda',
  LIVESTREAMS_CONCLUDED: 'The live stream has concluded',
  VIDEO_NOT_FOUND: 'Video not found',
  CLEAR_BUTTON: 'Clear',
  SEARCH_KEYWORD_PLACEHOLDER: 'By Keyword',
  SEARCH_NAME_PLACEHOLDER: 'Enter name to search...',
  SEARCH_PLACEHOLDER: 'Search',
  REMOVE_QUESITON: 'Remove question',
  REMOVE_QUESITON_MESSAGE: 'Do you want to remove this question?',
  REMOVE_RESOURCE: 'Remove resource',
  REMOVE_RESOURCE_MESSAGE: 'Do you want to remove this resource?',
  RATING_SAVED: 'Rating saved',
  EVENT_SAVED: 'Event Connect With Sponsor Email',
  SUCCESS: 'Success',
  FAILED: 'Failed',
  CHECK_CONNECTION: 'Please, check your connection',
  SOMETHING_WENT_WRONG: 'Oops, Something went wrong !!!',
  QAPOLLING: 'Q&A/Polling',
  NOTES: 'Notes',
  REMOVE_FROM_SHORT_LIST: 'Remove from shortlist',
  ADD_TO_FAVOURITE: 'Add to favourite',
  RESOURCES: 'Resources',
  ABOUT: 'About',
  TEAMS: 'Teams',
  RATING: 'Rating',
  REPLY: 'Reply',
  WATCHVIDEO: 'Watch video',
  PLAY: 'Play',
  FILM: 'film',
  SESSION: 'Session',
  TALK: 'Talk',
  EXHIBITOR: 'Exhibitor',
  SPONSOR: 'Sponsor',
  THEMES: 'Themes',
  OUR_DISCUSSION_TOPICS: 'Our discussion topics',
  CONNECT_WITH_SPONSOR: 'Connect With Sponsor',
  CONNECT_WITH_EVENT_SPONSOR: 'Connect With Event Sponsor',
  PASSWORD: 'Password',
  EMAIL: 'Email',
  SIGN_IN: 'Sign In',
  SIGN_UP: 'Sign Up',
  ERROR_LOGIN: 'Login Failed',
  TAP_TO_RELOAD: 'Tap to reload',
  TALKS: 'Talks',
  SESSION_TALKS: 'Session Talks',
  SESSION_TOPIC: 'Session Topic',
  NOTE_PLACEHOLDER: 'Leave your note...',
  NOTE: 'Note',
  REMOVE_NOTE: 'Remove note',
  REMOVE_NOTE_MESSAGE: 'Do you want to remove this note?',
  SETTING: 'Setting',
  SURVEY: 'Survey',
  SAVE_BUTTON: 'Save',
  EVENTS: 'Events',
  VIEW_ON_WEB: 'View on web',
  SELECT_IMAGE: 'Select Image',
  CHAT_NAME: 'Chat Name',
  TO: 'To',
  INVITE_MEMBERS: 'Invite new members',
  FILTERS: 'Filters',
  ANNOUNNCEMENT: 'Announcement',
  CONTENT: 'Content',
  TEXT_DEFAULT: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
  Lorem Ipsum has been the industry's standard dummy text ever since the 1500s`,
  BIO: 'Bio',
  ADD_FIELD: 'Add field',
  REMOVE_FIELD: 'Remove field',
  FIELD_LABEL: 'Field label',
  FIELD_TYPE: 'Field type',
  FIELD_MULTIPLE_OPTIONS: 'Multiple select options',
  UPLOADING: 'Uploading ...',
  UPLOAD_FAIL: 'Upload fail',
  TALK_TYPE: 'Talk Type',
  VIDEO_NOT_UPLOAD: 'Video did not upload',
  VIDEO_NOT_UPLOAD_SKIP: 'Submit without video',
  VIDEO_NOT_UPLOAD_CANCEL: 'Wait for upload video',
  TERMS_AND_CONDITIONS: 'Terms and Conditions',
  PRIVACY_POLICY: 'Privacy Policy',
  ABOUT_TITLE: 'Powered by Delegate Connect',
  ABOUT_BODY: 'Next generation software for scaling technology events',
  ABOUT_BUTTON: 'See Delegate Connect',
  SEEALL: 'See all',
  CHAIRPEOPLE: 'Chair People',
  ATTENDEES: 'Attendees',
  APPLYFILTERS: 'Apply Filters',
  WORKSHOP: 'Workshop',
};

export default message;

export const FORMS = {
  HOW_CAN_WE_HELP: 'HOW CAN WE HELP?',
  COMPANY_NAME: "COMPANY'S NAME",
  COMPANY_NAME_HINT: 'Min: 3 - Max: 80',
  NAME_ON_BOTH: 'NAME ON BOOTH',
  NAME_ON_BOTH_HINT:
    'The name for your booth, if different to your Company Name',
  COMPANY_ADDRESS: 'WHERE IS YOUR COMPANY BASED?',
  EXHIBITION_DESCRIBE: 'DESCRIBE YOUR EXHIBITION IN ONE SENTENCE',
  EXHIBITION_DESCRIBE_HINT:
    'A short sentence to be displayed with your Profile',
  COMPANY_OVERVIEW: 'COMPANY OVERVIEW',
  COMPANY_OVERVIEW_HINT: 'A short overview for the Profile page',
  COMPANY_WEBSITE: 'COMPANY WEBSITE',
  WEBSITE_HINT: 'Must include http:// or https://',
  EMAIL: 'CONTACT EMAIL',
  PHONE: 'PHONE NUMBER',
  FACEBOOK: 'FACEBOOK (OPTIONAL)',
  TWITTER: 'TWITTER (OPTIONAL)',
  INSTAGRAM: 'INSTAGRAM (OPTIONAL)',
  GITHUB: 'GITHUB (OPTIONAL)',
  LINKEDIN: 'LINKEDIN (OPTIONAL)',
  WECHAT: 'WECHAT (OPTIONAL)',
  LINE: 'LINE (OPTIONAL)',
  SKYPE: 'SKYPE (OPTIONAL)',
  ANGELLIST: 'ANGELLIST (OPTIONAL)',
  FEATURED_VIDEO: 'FEATURED VIDEO',
  FEATURED_VIDEO_HINT:
    'Use the File Upload below to upload and automatically link a featured video.' +
    ' Maximum file size: 100MB. Links to Youtube/Vimeo are NOT supported',
  PROFILE_IMAGE: 'PROFILE INDEX IMAGE',
  PROFILE_IMAGE_HINT:
    'Upload an image shown on the Index card (list view).' +
    ' Please note this is image is responsive and should not contain text, logos, or other assets you do not want altered/cut off.',
  COMPANY_LOGO: 'COMPANY LOGO',
  COMPANY_LOGO_HINT:
    'Provide your company logo as a JPG or PNG file. This image will be displayed against a white background',
  PROFILE_COVER: 'PROFILE COVER IMAGE',
  PROFILE_COVER_HINT:
    'Optionally upload a cover image shown on the Index card and as the header background.' +
    ' Please note this is image is responsive and should not contain text, logos, or other assets you do not want altered/cut off',
  PROFILE_COVER_COLOR: 'PROFILE COVER COLOUR',
  PROFILE_COVER_COLOR_PLACEHOLDER: '#0097DC',
  PROFILE_COVER_COLOR_HINT:
    "Set a custom HEX colour for the header background if you don't want to set an image. i.e. #0097DC",
  BOOTH_ARTWORK: 'BOOTH ARTWORK SUBMISSION',
  BOOTH_ARTWORK_HINT:
    'Upload one print ready artwork file for your Exhibitor booth art if requested by the organisers.' +
    ' Please follow the guidance provided by the organisers based on your booth dimensions and format',
  ARTWORK: 'ARTWORK',
  ADD_BOOTH_ARTWORK: 'ADD ARTWORK',
  REMOVE_BOOTH_ARTWORK: 'remove artwork',
  EXHIBITOR_DESCRIPTION: 'EXHIBITOR DESCRIPTION',
  EXHIBITOR_DESCRIPTION_HINT: 'This will be printed on your booth',
  ARTWORK_IMAGE: 'ARTWORK IMAGE',
  CHOOSE_FILES: 'CHOOSE FILES…',
  EXHIBITOR_CATEGORIES: 'EXHIBITOR CATEGORIES',
  EXHIBITOR_CATEGORIES_HINT: 'Select any categories that apply to your Company',
  TRACKS: 'TRACKS',
  EVENTS_EXHIBITING_AT: 'EVENTS EXHIBITING AT',
  LEAD_CAPTURE_FIELDS: 'LEAD CAPTURE FIELDS',
  LEAD_CAPTURE_FIELDS_HINT:
    'Add additional fields to the lead capture form. All contact details are automatically shared',
  LEAD_CAPTURE_FIELDS_MULTIPLE_HINT:
    'For multiple select fields, enter options separated by comma. ie: platinum,gold,silver,premier sponsor,bronze',
  UPLOAD_FILE_PLACEHOLDER: 'UPLOAD FILE',
  UPLOAD_IMAGE_PLACEHOLDER: 'UPLOAD IMAGE',
  UPLOAD_VIDEO_PLACEHOLDER: 'UPLOAD VIDEO',
  PICK_PLACEHOLDER: 'Tap to select',
  EXHIBITOR_STATUS: 'Exhibitor Status',
  STATUS_PUBLIC: 'Public',
  STATUS_PUBLIC_HINT:
    'Approves the Profile for publication. When set to No the Profile is not visible on the Platform',
  STATUS_FEATURED: 'Featured',
  STATUS_FEATURED_HINT:
    'When set to Yes, the Profile can be shown on the home page',
  LOGO_VIDEO: 'Logos & videos',
  EXHIBITOR_OVERVIEW: 'Exhibitor Overview',
  CONTACT_DETAILS: 'Contact Details',
  EXHIBITOR_ARTWORK: 'Exhibitor Artwork',
  EXHIBITOR_CONFIGURATION: 'Exhibitor Configuration',
  EXHIBITOR_USERS: 'Exhibitor Users',
  FORM_ABOUNT:
    "Let us know anything in particular you'd like to speak with us about",
  DESCRIPTION_ABSTRACT: 'DESCRIPTION/ABSTRACT',
  DESCRIPTION_CONFLICTS: 'LIST CONFLICTS OF INTEREST',
  CONFLICTS_ABOUNT: 'Please disclose all conflicts as per the event policy',
  DESCRIPTION_ABOUNT: 'Description of the Talk',
  TALKS_OVERVIEW: 'TALKS OVERVIEW',
  TALKS_AUTHORS: 'TALKS AUTHORS',
  TALKS_WEBCAST: 'WEBCAST, PUBLISHING APPROVAL',
  TALKS_CONFLICTS_INTEREST: 'DO YOU HAVE ANY CONFLICTS OF INTEREST',
  TALK_TITLE: 'TALK TITLE',
  TALK_VIDEO: 'TALK SUBMISSION VIDEO',
  VIDEO_PUBLISHING_APPROVAL: 'VIDEO ON DEMANF PUBLISHING APPROVAL',
  EPOSTER_PRESENTATION: 'EPOSTER PRESENTATION',
  TALK_THEMES: 'TALK THEMES',
  TALK_EVENTS: 'TALK EVENTS',
  SELECT_EVENT_TEXT: 'Select the event you are wanting to present at',
  TALK_VIDEO_HINT:
    'Provide a full URL to your Talk submission video adhering to the instructions provided' +
    ' by the event organisers. Alternatively, use the File Upload below to upload and automatically link the video. Maximum file size: 250MB',
  ONE_SENTENCE: 'ONE SENTENCE DESCRIBING THE COMPANY',
  ONE_SENTENCE_DESCRIPTION:
    'A short sentence to be displayed with your Profile',
  SPONSOR_OVERVIEW: 'Sponsor Overview',
  SPONSOR_CONFIGURATION: 'Sponsor Configuration',
  EVENTS: 'EVENTS',
};
